# Generated by Django 5.2.4 on 2026-07-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='media/images')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('tax_number', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=255)),
                ('address', models.CharField(help_text='Address', max_length=255)),
                ('tax_number', models.CharField(help_text='Tax Number', max_length=13)),
                ('branch', models.CharField(help_text='Branch', max_length=5)),
                ('email', models.CharField(help_text='Email', max_length=255)),
                ('phone', models.CharField(help_text='Phone', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(help_text='Contact Name', max_length=255)),
                ('phone', models.CharField(help_text='Phone', max_length=255)),
                ('address', models.CharField(help_text='Address', max_length=255)),
                ('subdistrict', models.CharField(help_text='Sub-district', max_length=255)),
                ('district', models.CharField(help_text='District', max_length=255)),
                ('province', models.CharField(help_text='Province', max_length=255)),
                ('zip_code', models.CharField(help_text='ZIP Code', max_length=255)),
            ],
        ),
    ]
