# Generated by Django 4.2.30 on 2026-07-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_customer_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
            ],
        ),
    ]
