# Generated by Django 4.2.30 on 2026-07-15 07:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_district_province_subdistrict_district_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='province',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='subdistrict',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='subdistrict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_addresses', to='company.subdistrict'),
        ),
    ]
