# Generated by Django 4.2.30 on 2026-07-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_shippingaddress_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdistrict',
            name='zip_code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
