# Generated by Django 4.2.30 on 2026-07-20 04:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_subdistrict_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdistrict',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='subdistrict',
            constraint=models.UniqueConstraint(fields=('name_th', 'zip_code'), name='unique_subdistrict_zip'),
        ),
    ]
