# Generated by Django 4.2.30 on 2026-07-24 03:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_subdistrict_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subdistrict',
            name='unique_subdistrict_zip',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='dept',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
