# Generated by Django 4.2.30 on 2026-07-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_subdistrict_unique_subdistrict_zip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='alley',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='road',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
